spring.application.name=u5-w1-d4-compito
# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/pizzeria_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate
spring.jpa.hibernate.ddl-auto=update
